# Generated by Django 5.1.4 on 2025-03-03 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivedinventory',
            old_name='descreption',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='archivedinventory',
            name='original_inventory_id',
        ),
    ]
