# Generated by Django 5.1.4 on 2025-06-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0002_systemsettings_auto_update_systemsettings_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='inactive_threshold_days',
            field=models.IntegerField(default=180),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='slow_threshold_days',
            field=models.IntegerField(default=30),
        ),
    ]
