# Generated by Django 5.1.4 on 2025-12-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0003_systemsettings_inactive_threshold_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='selected_suppliers',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='available_suppliers',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='stock_suppliers',
            field=models.JSONField(default=list),
        ),
    ]
