# Generated by Django 5.1.4 on 2025-02-09 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='cost',
            new_name='price',
        ),
    ]
