# Generated by Django 5.1.4 on 2025-01-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventoryitem_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='date_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
