# Generated by Django 5.1.4 on 2025-02-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryitem_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
