# Generated by Django 5.1.4 on 2025-08-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventoryitem_break_qty_a_inventoryitem_price_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='supplier',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
