# Generated by Django 5.1.4 on 2025-08-19 09:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm_accounts', '0006_alter_crminteraction_direction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('reminded', 'Reminded'), ('won', 'Won'), ('lost', 'Lost'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('crm_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='crm_accounts.crmaccount')),
                ('interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='crm_accounts.crminteraction')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpn', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('qty_offered', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('date_code', models.CharField(blank=True, max_length=50)),
                ('lead_time', models.PositiveIntegerField(blank=True, help_text='Lead time in days', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_source', models.CharField(blank=True, max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotes.quote')),
            ],
        ),
    ]
