# Generated by Django 5.1.4 on 2025-06-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteitem',
            name='lead_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
