# Generated by Django 5.1.4 on 2025-08-10 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_quote_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteitem',
            name='lead_time',
            field=models.PositiveIntegerField(blank=True, help_text='Lead time in days', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
