# Generated by Django 5.1.4 on 2025-08-10 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_alter_quoteitem_lead_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteitem',
            name='lead_time',
        ),
    ]
