# Generated by Django 5.1.4 on 2025-05-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crminteraction',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='crmtask',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crmtask',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='crmtask',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
