# Generated by Django 5.1.4 on 2025-06-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounts', '0002_crminteraction_title_crmtask_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crminteraction',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
