# Generated by Django 5.1.4 on 2025-06-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounts', '0003_alter_crminteraction_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='crminteraction',
            name='direction',
            field=models.CharField(blank=True, choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], max_length=10, null=True),
        ),
    ]
