# Generated by Django 5.1.4 on 2025-06-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounts', '0005_crminteraction_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crminteraction',
            name='direction',
            field=models.CharField(blank=True, choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing'), ('mixed', 'Mixed')], max_length=10, null=True),
        ),
    ]
