# Generated by Django 5.1.4 on 2025-08-24 10:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounts', '0006_alter_crminteraction_direction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='crminteraction',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='crminteraction',
            index=models.Index(fields=['account', 'thread_id'], name='idx_acc_thread'),
        ),
        migrations.AddIndex(
            model_name='crminteraction',
            index=models.Index(fields=['account', 'timestamp'], name='idx_acc_ts'),
        ),
    ]
