# Generated by Django 5.1.4 on 2025-08-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounts', '0007_alter_crminteraction_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
