# Generated by Django 5.1.4 on 2025-10-31 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_accounts', '0008_crmaccount_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crmaccount',
            options={'permissions': [('access_crm', 'Can access CRM module')]},
        ),
    ]
