# Generated by Django 5.1.4 on 2025-02-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='stock_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
