# Generated by Django 5.1.4 on 2025-02-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqs', '0002_rfq_stock_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
