# Generated by Django 5.1.4 on 2024-12-08 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('rfqs', '0002_alter_rfq_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='qty_requested',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='target_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
