# Generated by Django 5.1.4 on 2024-12-18 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('contacts', '0002_alter_contact_company_alter_contact_email'),
        ('rfqs', '0003_alter_rfq_customer_alter_rfq_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company'),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact'),
        ),
    ]
