# Generated by Django 5.1.4 on 2025-02-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqs', '0003_rfq_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq',
            name='source',
            field=models.CharField(choices=[('Website', 'Website'), ('NetComponents', 'NetComponents'), ('IC Source', 'ICSource'), ('Private', 'Private')], max_length=255),
        ),
    ]
