# Generated by Django 5.1.4 on 2025-02-17 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqs', '0005_alter_rfq_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='auto_quote_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfq',
            name='parent_rfq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rfqs.rfq'),
        ),
    ]
