# Generated by Django 5.1.4 on 2024-12-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqs', '0005_rename_dc_requested_rfq_date_code_rfq_qty_offered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq',
            name='source',
            field=models.CharField(choices=[('website', 'Website'), ('netCOMPONENTS', 'NetComponents'), ('IC Source', 'ICSource'), ('Private', 'Private')], max_length=255),
        ),
    ]
