# Generated by Django 5.1.4 on 2025-02-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqs', '0006_rfq_auto_quote_deadline_rfq_parent_rfq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq',
            name='source',
            field=models.CharField(choices=[('Website', 'Website'), ('netComponents', 'netComponents'), ('IC Source', 'IC Source'), ('Private', 'Private')], max_length=255),
        ),
    ]
