# Generated by Django 5.1.4 on 2025-05-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqs', '0009_alter_rfq_target_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq',
            name='offered_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
