# Generated by Django 5.1.4 on 2026-05-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_options'),
        ('contacts', '0001_initial'),
        ('inventory', '0007_alter_inventoryitem_supplier'),
        ('rfqs', '0010_alter_rfq_offered_price'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rfq',
            index=models.Index(fields=['status', '-created_at'], name='rfq_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='rfq',
            index=models.Index(fields=['created_at'], name='rfq_created_idx'),
        ),
        migrations.AddIndex(
            model_name='rfq',
            index=models.Index(fields=['status'], name='rfq_status_idx'),
        ),
    ]
