# Generated by Django 5.1.4 on 2025-02-18 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0002_rename_icsource_enabled_usersettings_export_icsource_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettings',
            old_name='file_format',
            new_name='export_file_format',
        ),
    ]
