# Generated by Django 5.1.4 on 2025-02-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0003_rename_file_format_usersettings_export_file_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='selected_suppliers',
            field=models.JSONField(default=list),
        ),
    ]
