# Generated by Django 5.1.4 on 2025-05-05 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_connections', '0001_initial'),
        ('usersettings', '0006_usersettings_created_at_usersettings_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='rfq_email_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfq_connection', to='email_connections.emailconnection'),
        ),
    ]
