# Generated by Django 5.1.4 on 2025-05-12 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0007_usersettings_rfq_email_connection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='auto_update',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='export_file_format',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='export_icsource',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='export_inventory',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='export_netcomponents',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='icsource_max_available',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='icsource_max_stock',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='last_export_date',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='netcomponents_max_available',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='netcomponents_max_stock',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='selected_suppliers',
        ),
    ]
