# Generated by Django 5.1.4 on 2025-08-04 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_connections', '0001_initial'),
        ('usersettings', '0008_remove_usersettings_auto_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='crm_email_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_connection', to='email_connections.emailconnection'),
        ),
    ]
