# Generated by Django 5.1.4 on 2026-05-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('awaiting', 'Awaiting'), ('awaiting_payment', 'Awaiting Payment'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('shipped', 'Shipped'), ('returned', 'Returned')], default='new', max_length=32),
        ),
    ]
