# Generated by Django 5.1.4 on 2025-12-06 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_website'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': [('access_companies', 'Can access Companies module')]},
        ),
    ]
